/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.orm.view;

import ffos.orm.controller.ObradaOsoba;
import ffos.orm.model.Osoba;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jure
 */
public class FormaOsoba extends javax.swing.JFrame {
 private ObradaOsoba oo; 
  
    public FormaOsoba() {
        initComponents();
        oo = new ObradaOsoba();
    ucitaj();

    }
    
    private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Osoba o : oo.getMjesto()) {
            m.addElement(o);
        }
        lstOsoba.setModel(m);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstOsoba = new javax.swing.JList<>();
        txtImeOsoba = new javax.swing.JTextField();
        txtPrezimeOsoba = new javax.swing.JTextField();
        btnDodajOsoba = new javax.swing.JButton();
        btnBrisanjeOsoba = new javax.swing.JButton();
        btnPromijeniOsoba = new javax.swing.JButton();
        cmbPostanskiBroj = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstOsoba);

        txtImeOsoba.setText("Ime");
        txtImeOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeOsobaActionPerformed(evt);
            }
        });

        txtPrezimeOsoba.setText("Prezime");
        txtPrezimeOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeOsobaActionPerformed(evt);
            }
        });

        btnDodajOsoba.setText("Dodaj");
        btnDodajOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajOsobaActionPerformed(evt);
            }
        });

        btnBrisanjeOsoba.setText("Obriši");
        btnBrisanjeOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeOsobaActionPerformed(evt);
            }
        });

        btnPromijeniOsoba.setText("Promijeni");
        btnPromijeniOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromijeniOsobaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPromijeniOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDodajOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBrisanjeOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtImeOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrezimeOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(cmbPostanskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtImeOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPrezimeOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbPostanskiBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDodajOsoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPromijeniOsoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrisanjeOsoba)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtImeOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeOsobaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeOsobaActionPerformed

    private void btnDodajOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajOsobaActionPerformed
         Osoba o = new Osoba();
        o.setIme(txtImeOsoba.getText());
           o.setIme(txtPrezimeOsoba.getText());
        oo.dodajOsoba(o);
        ucitaj();
    }//GEN-LAST:event_btnDodajOsobaActionPerformed

    private void btnPromijeniOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromijeniOsobaActionPerformed
                try {
            DefaultListModel m = (DefaultListModel)lstOsoba.getModel();
      
    Osoba o  = (Osoba)m.get(lstOsoba.getSelectedIndex());
            o.setIme(txtImeOsoba.getText());
             o.setIme(txtPrezimeOsoba.getText());
            oo.dodajOsoba(o);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_btnPromijeniOsobaActionPerformed

    private void btnBrisanjeOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeOsobaActionPerformed
        try {
            DefaultListModel m = (DefaultListModel)lstOsoba.getModel();
          Osoba o = (Osoba)m.get(lstOsoba.getSelectedIndex());
            o.setIme(txtImeOsoba.getText());
               o.setIme(txtPrezimeOsoba.getText());
            oo.brisanjeOsoba(o);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_btnBrisanjeOsobaActionPerformed

    private void txtPrezimeOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeOsobaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeOsobaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanjeOsoba;
    private javax.swing.JButton btnDodajOsoba;
    private javax.swing.JButton btnPromijeniOsoba;
    private javax.swing.JComboBox<String> cmbPostanskiBroj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstOsoba;
    private javax.swing.JTextField txtImeOsoba;
    private javax.swing.JTextField txtPrezimeOsoba;
    // End of variables declaration//GEN-END:variables
}
