/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.orm.view;

import ffos.orm.controller.ObradaMjesta;
import ffos.orm.controller.ObradaOsoba;
import ffos.orm.model.Mjesto;
import ffos.orm.model.Osoba;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jure
 */
public class FormaMjesto extends javax.swing.JFrame {

    private ObradaMjesta omj; 
    
    public FormaMjesto() {
        initComponents();
        omj = new ObradaMjesta();
    ucitaj();
    }
   private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Mjesto mj : omj.getMjesto()) {
            m.addElement(mj);
        }
        lstMjesto.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDodajOsoba = new javax.swing.JButton();
        btnBrisanjeOsoba = new javax.swing.JButton();
        btnPromijeniOsoba = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMjesto = new javax.swing.JList<>();
        txtNazivMjesto = new javax.swing.JTextField();
        txtPostanskiBrojMjesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDodajOsoba.setText("Dodaj");
        btnDodajOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajOsobaActionPerformed(evt);
            }
        });

        btnBrisanjeOsoba.setText("Obriši");
        btnBrisanjeOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeOsobaActionPerformed(evt);
            }
        });

        btnPromijeniOsoba.setText("Promijeni");
        btnPromijeniOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromijeniOsobaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstMjesto);

        txtNazivMjesto.setText("Naziv");
        txtNazivMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivMjestoActionPerformed(evt);
            }
        });

        txtPostanskiBrojMjesto.setText("Poštanski broj ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPostanskiBrojMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtNazivMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPromijeniOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDodajOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBrisanjeOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtNazivMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPostanskiBrojMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajOsoba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPromijeniOsoba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrisanjeOsoba)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajOsobaActionPerformed
      Mjesto mj = new Mjesto();
        mj.setNaziv(txtNazivMjesto.getText());
        mj.setPostanski_broj(txtPostanskiBrojMjesto.getText());
        omj.dodajMjesto(mj);
        ucitaj();
    }//GEN-LAST:event_btnDodajOsobaActionPerformed

    private void btnBrisanjeOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeOsobaActionPerformed
        try {
            DefaultListModel m = (DefaultListModel)lstMjesto.getModel();
            Mjesto mj = (Mjesto)m.get(lstMjesto.getSelectedIndex());
            mj.setNaziv(txtNazivMjesto.getText());
            
            omj.brisanjeMjesta(mj);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_btnBrisanjeOsobaActionPerformed

    private void btnPromijeniOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromijeniOsobaActionPerformed
        try {
            DefaultListModel m = (DefaultListModel)lstMjesto.getModel();

            Mjesto mj  = (Mjesto)m.get(lstMjesto.getSelectedIndex());
            mj.setNaziv(txtNazivMjesto.getText());
            
            omj.dodajMjesto(mj);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_btnPromijeniOsobaActionPerformed

    private void txtNazivMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivMjestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivMjestoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanjeOsoba;
    private javax.swing.JButton btnDodajOsoba;
    private javax.swing.JButton btnPromijeniOsoba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMjesto;
    private javax.swing.JTextField txtNazivMjesto;
    private javax.swing.JTextField txtPostanskiBrojMjesto;
    // End of variables declaration//GEN-END:variables
}
