/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.orm.view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Korisnik
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDarivanje = new javax.swing.JButton();
        btnOsoba = new javax.swing.JButton();
        btnMjesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDarivanje.setText("Darivanje");
        btnDarivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarivanjeActionPerformed(evt);
            }
        });

        btnOsoba.setText("Osoba");
        btnOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsobaActionPerformed(evt);
            }
        });

        btnMjesto.setText("Mjesto");
        btnMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMjestoActionPerformed(evt);
            }
        });

        jLabel1.setText("Izbornik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarivanje))
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(btnDarivanje)
                .addGap(34, 34, 34)
                .addComponent(btnOsoba)
                .addGap(33, 33, 33)
                .addComponent(btnMjesto)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarivanjeActionPerformed
        new FormaDarivanje().setVisible(true); 
        
    }//GEN-LAST:event_btnDarivanjeActionPerformed

    private void btnOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsobaActionPerformed
      new FormaOsoba().setVisible(true);
    }//GEN-LAST:event_btnOsobaActionPerformed

    private void btnMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMjestoActionPerformed
       new FormaMjesto().setVisible(true);
    }//GEN-LAST:event_btnMjestoActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarivanje;
    private javax.swing.JButton btnMjesto;
    private javax.swing.JButton btnOsoba;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
